### PR TITLE
Updated solidity to 0.6.2 

### PR DESCRIPTION
**Pull request by g-r-a-n-t**
This is part of some other work I'm doing [here](https://github.com/ethereum/rust-vyper/pull/11).

### CODE REVIEW

**Comment by spalladino** [comment]
Hey there! I'm interested in picking this up for a side project, and when trying to run the tests on this branch with `cargo test` I'm getting the following error after the 2nd call to `compile`:

```
{"errors":[{"component":"general","formattedMessage":"Internal exception in StandardCompiler::compile: /solidity/libsolidity/interface/CompilerStack.cpp(90): Throw in function solidity::frontend::CompilerStack::CompilerStack(const Callback&)\nDynamic exception type: boost::exception_detail::clone_impl<solidity::langutil::InternalCompilerError>\nstd::exception::what: You shall not have another CompilerStack aside me.\n[solidity::util::tag_comment*] = You shall not have another CompilerStack aside me.\n","message":"Internal exception in StandardCompiler::compile: /solidity/libsolidity/interface/CompilerStack.cpp(90): Throw in function solidity::frontend::CompilerStack::CompilerStack(const Callback&)\nDynamic exception type: boost::exception_detail::clone_impl<solidity::langutil::InternalCompilerError>\nstd::exception::what: You shall not have another CompilerStack aside me.\n[solidity::util::tag_comment*] = You shall not have another CompilerStack aside me.\n","severity":"error","type":"InternalCompilerError"}]}
```

Where the `You shall not have another CompilerStack aside me` seems to come from [here](https://github.com/ethereum/solidity/blob/101c47bfb94122c387e90d53b115856ae9ba8a7f/libsolidity/interface/CompilerStack.cpp#L90).

@g-r-a-n-t did you face this issue as well? @axic what would be needed to fully clear out the outstanding compiler stack, so as to call `compile` more than once and run multiple tests? grant seems to be properly calling `free` on the compile result and a full `reset` as well (see [here](https://github.com/axic/solc-rust/pull/1/files#diff-b4aea3e418ccdb71239b96952d9cddb6R46-R47)). What else may be missing?

**Comment by g-r-a-n-t** [comment]
Hi @spalladino, thanks for reaching out!

More details on why this is happening can be found [here](https://github.com/ethereum/solidity/pull/8411). Basically, we can't call solc from multiple threads anymore. This is problematic with Rust tests because they run in parallel by default.

I think it would be best to just lock calls to `solidity_compile` within solc-rust, effectively shielding users from the fact that solc is not re-entrant. It should be pretty straight forward. Once this is fixed, I think we're good to merge this.

Let me know if you would like more info or suggestions :)

**Comment by spalladino** [comment]
Cool, thanks a lot Grant! Just gave a shot at it [here](https://github.com/axic/solc-rust/pull/1). Let me know if you'd prefer if I sent the PR to your fork instead.

**Comment by g-r-a-n-t** [comment]
see #2

**Pull request closed without merging**
